### ISSUE TITLE
Level 1 Reports not working

### ISSUE THREAD

**Issue by mpdougherty** [FluvialGeomorph/fluvgeo#26]
Here is the error message reported by @tadarby12

<img width="653" alt="MicrosoftTeams-image (3)" src="https://github.com/FluvialGeomorph/fluvgeo/assets/43588467/4ddd3319-ae35-46dc-9592-fec253ffface">

**Comment by mpdougherty** [comment]
Since this is happening so late in the report, the issue is probably with the `map_xs` function that is the oldest of the mapping functions and is therefore still using `sp` which is ending end of life and throwing messages.

**Comment by bchileen** [comment]
Started moving through codebase and changing out SP and rgdal dependencies to sf and raster functions.

**Comment by bchileen** [comment]
see latest release, test and report back on if the issue has been resolved

**Comment by bchileen** [comment]
issue resolved with [v0.1.46](https://github.com/FluvialGeomorph/fluvgeo/releases/tag/v0.1.46) release
